### ISSUE TITLE
[Storyboard] Unknown class _TtC6Y5Lock16AHDownloadButton in Interface Builder file

### ISSUE THREAD

**Issue by mehulparmar4ever** [amerhukic/AHDownloadButton#10]
Tried almost eveything. Still getting this error.

<img width="1118" alt="Screenshot 2020-04-30 at 10 35 26 AM" src="https://user-images.githubusercontent.com/7687920/80674002-5314f580-8ace-11ea-9d5b-e03e0e4d318e.png">

**Comment by amerhukic** [comment]
This is most likely related to the Storyboard file that uses the `AHDownloadButton`. I will close this issue. If it keeps happening please provide an example project where I can reproduce it and I will fix it.
