### ISSUE TITLE
Unable to leave animationDispatchGroup if app goes to background...

### ISSUE THREAD

**Issue by ykying** [amerhukic/AHDownloadButton#11]
Unable to leave animationDispatchGroup if app goes to background then back...and the UI is stuck with "startDownload" state

AHDownloadButton+StateTransitionAnimation.swift
```
// My simple fix

//From:
let completion: (Bool) -> Void = { completed in
    guard completed else { return }
    self.resetStateViews(except: newState)
    self.animationDispatchGroup.leave()
}

//To:
let completion: (Bool) -> Void = { completed in
    self.resetStateViews(except: newState)
    self.animationDispatchGroup.leave()
    guard completed else { return }
}
```

**Comment by ykying** [comment]
Same as app goes to background, the animation can't stop with a "completed" state, the flag value is "false", and it makes "isAnimating" equals to true all the time, and not able to animate again during "downloading" state.

ProgressCircleView.swift Line:83
```
//From
isAnimating = !flag
//To
isAnimating = false

**Comment by amerhukic** [comment]
Thank you @ykying for reporting this issue. It has been fixed in the latest release. Sorry for waiting this long.
